module.exports = {
  LIST_TYPE_LIKES: 'likes',
  LIST_TYPE_FOLLOWINGS: 'followings',
  LIST_TYPE_PLAYLISTS: 'playlists',

  LIST_SORT_OPTION_OLDEST: 'Oldest',
  LIST_SORT_OPTION_NEWEST: 'Newest',
  LIST_SORT_OPTION_ALPHABETIC: 'A to Z',
  LIST_SORT_OPTION_STATUS: 'Status',

  STATUS_SYNCHRONIZED: 'synchronized',
  STATUS_WAITING: 'waiting',
  STATUS_EXIST: 'exist',
  STATUS_ERROR: 'error',

  JOB_TYPE_ALL: 'JOB_TYPE_ALL',
  JOB_TYPE_LIKES: 'JOB_TYPE_LIKES',
  JOB_TYPE_FOLLOWINGS: 'JOB_TYPE_FOLLOWINGS'
};
