const
  LIST_TYPE_LIKES = 'likes',
  LIST_TYPE_FOLLOWINGS = 'followings',
  LIST_TYPE_PLAYLISTS = 'playlists',

  LIST_SORT_OPTION_OLDEST = 'Oldest',
  LIST_SORT_OPTION_NEWEST = 'Newest',
  LIST_SORT_OPTION_ALPHABETIC = 'A to Z',
  LIST_SORT_OPTION_STATUS = 'Status',

  STATUS_SYNCHRONIZED = 'synchronized',
  STATUS_WAITING = 'waiting',
  STATUS_EXIST = 'exist',
  STATUS_ERROR = 'error',

  TASK_TYPE_SELECTED = 'TASK_TYPE_SELECTED',
  TASK_TYPE_FILTERED = 'TASK_TYPE_FILTERED',
  TASK_SUBTYPE_ALL = 'TASK_SUBTYPE_ALL',
  TASK_SUBTYPE_ALL_LIKES = 'TASK_SUBTYPE_ALL_LIKES',
  TASK_SUBTYPE_ALL_FOLLOWINGS = 'TASK_SUBTYPE_ALL_FOLLOWINGS',
  TASK_SUBTYPE_ALL_PLAYLISTS = 'TASK_SUBTYPE_ALL_PLAYLISTS';

export {
  LIST_TYPE_LIKES,
  LIST_TYPE_FOLLOWINGS,
  LIST_TYPE_PLAYLISTS,

  LIST_SORT_OPTION_OLDEST,
  LIST_SORT_OPTION_NEWEST,
  LIST_SORT_OPTION_ALPHABETIC,
  LIST_SORT_OPTION_STATUS,

  STATUS_SYNCHRONIZED,
  STATUS_WAITING,
  STATUS_EXIST,
  STATUS_ERROR,

  TASK_TYPE_SELECTED,
  TASK_TYPE_FILTERED,
  TASK_SUBTYPE_ALL,
  TASK_SUBTYPE_ALL_LIKES,
  TASK_SUBTYPE_ALL_FOLLOWINGS,
  TASK_SUBTYPE_ALL_PLAYLISTS
};
