module.exports = {
  SOCKET_INITIALIZATION_START: 'SOCKET_INITIALIZATION_START ',
  SOCKET_INITIALIZATION_ERROR: 'SOCKET_INITIALIZATION_ERROR',
  SOCKET_INITIALIZATION_ONDATA: 'SOCKET_INITIALIZATION_ONDATA',
  SOCKET_INITIALIZATION_SUCCESS: 'SOCKET_INITIALIZATION_SUCCESS',

  SOCKET_LIKES_GET: 'SOCKET_GET_USER_LIKES',
  SOCKET_LIKES_ONDATA: 'SOCKET_LIKES_ONDATA',
  SOCKET_LIKES_GET_ERROR: 'SOCKET_LIKES_GET_ERROR',
  SOCKET_FOLLOWINGS_GET: 'SOCKET_FOLLOWINGS_GET',
  SOCKET_FOLLOWINGS_ONDATA: 'SOCKET_FOLLOWINGS_ONDATA',

  SOCKET_SYNC_STAT_START: 'SOCKET_SYNC_STAT_START',
  SOCKET_SYNC_STAT_GET: 'SOCKET_SYNC_STAT_GET',
  SOCKET_SYNC_STAT_ONDATA: 'SOCKET_SYNC_STAT_ONDATA',
  SOCKET_SYNC_STAT_SUCCESS: 'SOCKET_SYNC_STAT_SUCCESS',
  SOCKET_SYNC_STAT_ERROR: 'SOCKET_SYNC_STAT_ERROR',

  SOCKET_JOB_ADD: 'SOCKET_JOB_ADD',
  SOCKET_JOB_ADD_ERROR: 'SOCKET_JOB_ADD_ERROR',
  SOCKET_JOB_ADD_SUCCESS: 'SOCKET_JOB_ADD_SUCCESS',
  SOCKET_JOB_EXEC_START: 'SOCKET_JOB_EXEC_START',
  SOCKET_JOB_EXEC_ERROR: 'SOCKET_JOB_EXEC_ERROR',
  SOCKET_JOB_EXEC_SUCCESS: 'SOCKET_JOB_EXEC_SUCCESS',
  SOCKET_JOB_EXEC_CANCEL: 'SOCKET_JOB_EXEC_CANCEL',
  SOCKET_JOB_REMOVE: 'SOCKET_JOB_REMOVE',

  SOCKET_SYNC_ITEM_SUCCESS: 'SOCKET_SYNC_ITEM_SUCCESS',
  SOCKET_SYNC_ITEM_ERROR: 'SOCKET_SYNC_ITEM_ERROR',

  SOCKET_TO_MANY_REQUESTS_ERROR: 'SOCKET_TO_MANY_REQUESTS_ERROR'
};
