const
  SOCKET_INITIALIZATION_START = 'SOCKET_INITIALIZATION_START ',
  SOCKET_INITIALIZATION_ERROR = 'SOCKET_INITIALIZATION_ERROR',
  SOCKET_INITIALIZATION_ONDATA = 'SOCKET_INITIALIZATION_ONDATA',
  SOCKET_INITIALIZATION_SUCCESS = 'SOCKET_INITIALIZATION_SUCCESS',

  SOCKET_ITEMS_GET = 'SOCKET_ITEMS_GET',
  SOCKET_ITEMS_ONDATA = 'SOCKET_ITEMS_ONDATA',
  SOCKET_ITEMS_GET_ERROR = 'SOCKET_ITEMS_GET_ERROR',

  SOCKET_SYNC_STAT_START = 'SOCKET_SYNC_STAT_START',
  SOCKET_SYNC_STAT_GET = 'SOCKET_SYNC_STAT_GET',
  SOCKET_SYNC_STAT_ONDATA = 'SOCKET_SYNC_STAT_ONDATA',
  SOCKET_SYNC_STAT_SUCCESS = 'SOCKET_SYNC_STAT_SUCCESS',
  SOCKET_SYNC_STAT_ERROR = 'SOCKET_SYNC_STAT_ERROR',

  SOCKET_TASK_ADD = 'SOCKET_TASK_ADD',
  SOCKET_TASK_ADD_ERROR = 'SOCKET_TASK_ADD_ERROR',
  SOCKET_TASK_ADD_SUCCESS = 'SOCKET_TASK_ADD_SUCCESS',
  SOCKET_TASK_EXEC_START = 'SOCKET_TASK_EXEC_START',
  SOCKET_TASK_EXEC_ERROR = 'SOCKET_TASK_EXEC_ERROR',
  SOCKET_TASK_EXEC_SUCCESS = 'SOCKET_TASK_EXEC_SUCCESS',
  SOCKET_TASK_EXEC_CANCEL = 'SOCKET_TASK_EXEC_CANCEL',
  SOCKET_TASK_REMOVE = 'SOCKET_TASK_REMOVE',

  SOCKET_SYNC_ITEM_SUCCESS = 'SOCKET_SYNC_ITEM_SUCCESS',
  SOCKET_SYNC_ITEM_ERROR = 'SOCKET_SYNC_ITEM_ERROR',

  SOCKET_TO_MANY_REQUESTS_ERROR = 'SOCKET_TO_MANY_REQUESTS_ERROR';

export {
  SOCKET_INITIALIZATION_START,
  SOCKET_INITIALIZATION_ERROR,
  SOCKET_INITIALIZATION_ONDATA,
  SOCKET_INITIALIZATION_SUCCESS,

  SOCKET_ITEMS_GET,
  SOCKET_ITEMS_ONDATA,
  SOCKET_ITEMS_GET_ERROR,

  SOCKET_SYNC_STAT_START,
  SOCKET_SYNC_STAT_GET,
  SOCKET_SYNC_STAT_ONDATA,
  SOCKET_SYNC_STAT_SUCCESS,
  SOCKET_SYNC_STAT_ERROR,

  SOCKET_TASK_ADD,
  SOCKET_TASK_ADD_ERROR,
  SOCKET_TASK_ADD_SUCCESS,
  SOCKET_TASK_EXEC_START,
  SOCKET_TASK_EXEC_ERROR,
  SOCKET_TASK_EXEC_SUCCESS,
  SOCKET_TASK_EXEC_CANCEL,
  SOCKET_TASK_REMOVE,

  SOCKET_SYNC_ITEM_SUCCESS,
  SOCKET_SYNC_ITEM_ERROR,

  SOCKET_TO_MANY_REQUESTS_ERROR
};
