const LIST_TYPE_LIKES = 'likes';
const LIST_TYPE_FOLLOWINGS = 'followings';
const LIST_TYPE_PLAYLISTS = 'playlists';

const LIST_SORT_OPTION_OLDEST = 'Oldest';
const LIST_SORT_OPTION_NEWEST = 'Newest';
const LIST_SORT_OPTION_ALPHABETIC = 'A to Z';
const LIST_SORT_OPTION_STATUS = 'Status';

const STATUS_SYNCHRONIZED = 'synchronized';
const STATUS_WAITING = 'waiting';
const STATUS_EXIST = 'exist';
const STATUS_ERROR = 'error';

module.exports = {
  STATUS_ERROR,
  STATUS_EXIST,
  STATUS_WAITING,
  STATUS_SYNCHRONIZED,
  LIST_TYPE_FOLLOWINGS,
  LIST_TYPE_LIKES,
  LIST_TYPE_PLAYLISTS,
  LIST_SORT_OPTION_ALPHABETIC,
  LIST_SORT_OPTION_NEWEST,
  LIST_SORT_OPTION_OLDEST,
  LIST_SORT_OPTION_STATUS
};
