const SOCKET_INITIALIZATION_START = 'SOCKET_INITIALIZATION_START ',
  SOCKET_INITIALIZATION_FAIL = 'SOCKET_INITIALIZATION_FAIL',
  SOCKET_INITIALIZATION_SUCCESS = 'SOCKET_INITIALIZATION_SUCCESS'

module.exports = {
  SOCKET_INITIALIZATION_FAIL,
  SOCKET_INITIALIZATION_START,
  SOCKET_INITIALIZATION_SUCCESS
}
