const SOCKET_INITIALIZATION_START = 'SOCKET_INITIALIZATION_START ',
  SOCKET_INITIALIZATION_FAIL = 'SOCKET_INITIALIZATION_FAIL',
  SOCKET_INITIALIZATION_DATA_LOADED = 'SOCKET_INITIALIZATION_DATA_LOADED',
  SOCKET_INITIALIZATION_SUCCESS = 'SOCKET_INITIALIZATION_SUCCESS',

  SOCKET_GET_USER_LIKES = 'SOCKET_GET_USER_LIKES',
  SOCKET_USER_LIKES = 'SOCKET_GET_LIKES',
  SOCKET_USER_LIKES_ERROR = 'SOCKET_USER_LIKES_ERROR',
  SOCKET_GET_USER_FOLLOWINGS = 'SOCKET_GET_USER_FOLLOWINGS',
  SOCKET_USER_FOLLOWINGS = 'SOCKET_USER_FOLLOWINGS',

  SOCKET_SYNC_STATUS_START = 'SOCKET_SYNC_STATUS_START',
  SOCKET_SYNC_STATUS_GET = 'SOCKET_SYNC_STATUS_GET',
  SOCKET_SYNC_STATUS_DATA = 'SOCKET_SYNC_STATUS_DATA',
  SOCKET_SYNC_STATUS_SUCCESS = 'SOCKET_SYNC_STATUS_SUCCESS',
  SOCKET_SYNC_STATUS_FAIL = 'SOCKET_SYNC_STATUS_FAIL';

module.exports = {
  SOCKET_INITIALIZATION_FAIL,
  SOCKET_INITIALIZATION_START,
  SOCKET_INITIALIZATION_SUCCESS,
  SOCKET_INITIALIZATION_DATA_LOADED,

  SOCKET_GET_USER_LIKES,
  SOCKET_USER_LIKES,
  SOCKET_USER_LIKES_ERROR,
  SOCKET_GET_USER_FOLLOWINGS,
  SOCKET_USER_FOLLOWINGS,

  SOCKET_SYNC_STATUS_START,
  SOCKET_SYNC_STATUS_GET,
  SOCKET_SYNC_STATUS_DATA,
  SOCKET_SYNC_STATUS_FAIL,
  SOCKET_SYNC_STATUS_SUCCESS
};
